---
title: "Daniel Data Import Script"
format: html
---

```{r packages}
library(tidyverse)
library(rvest)
```

```{r}
alphabet <- LETTERS

men_scrape <- function(x){
   read_html(paste0('https://wot.fandom.com/wiki/Category:Men?from=', x))|>
     html_elements('li')|>
     html_element('.category-page__member-link')|>
     html_text2()
}

for (char in alphabet) {
  value <- men_scrape(char)
  assign(paste0('vector',char), value, envir = .GlobalEnv)
}

women_scrape <- function(x){
   read_html(paste0('https://wot.fandom.com/wiki/Category:Women?from=', x))|>
     html_elements('li')|>
     html_element('.category-page__member-link')|>
     html_text2()
}

for (char in alphabet) {
  value <- women_scrape(char)
  assign(paste0('1vector',char), value, envir = .GlobalEnv)
}

unknown_scrape <- function(x){
   read_html(paste0('https://wot.fandom.com/wiki/Category:Unknown_gender?from=', x))|>
     html_elements('li')|>
     html_element('.category-page__member-link')|>
     html_text2()
}

for (char in alphabet) {
  value <- unknown_scrape(char)
  assign(paste0('2vector',char), value, envir = .GlobalEnv)
}

```

```{r}
all_names <- c(vectorA, vectorB, vectorC, vectorD, vectorE, vectorF, vectorG, vectorH, vectorI, vectorJ, vectorK, vectorL, vectorM, vectorN, vectorO,
vectorP, vectorQ, vectorR, vectorS, vectorT, vectorU, vectorV, vectorW, vectorX, vectorY, vectorZ, `1vectorA`, `1vectorB`, `1vectorC`, `1vectorD`, `1vectorE`, `1vectorF`, `1vectorG`, `1vectorH`, `1vectorI`, `1vectorJ`, `1vectorK`, `1vectorL`, `1vectorM`, `1vectorN`, `1vectorO`,
`1vectorP`, `1vectorQ`, `1vectorR`, `1vectorS`, `1vectorT`, `1vectorU`, `1vectorV`, `1vectorW`, `1vectorX`, `1vectorY`, `1vectorZ`, `2vectorA`, `2vectorB`, `2vectorC`, `2vectorD`, `2vectorE`, `2vectorF`, `2vectorG`, `2vectorH`, `2vectorI`, `2vectorJ`, `2vectorK`, `2vectorL`, `2vectorM`, `2vectorN`, `2vectorO`,
`2vectorP`, `2vectorQ`, `2vectorR`, `2vectorS`, `2vectorT`, `2vectorU`, `2vectorV`, `2vectorW`, `2vectorX`, `2vectorY`, `2vectorZ`)|>
  tibble()|>
  drop_na()|>
  distinct()|>
  rename('names' = `c(...)`) -> all_names
```

```{r}
base_link <- ('https://wot.fandom.com/wiki/')
links <- sapply(all_names, function(x) paste0(base_link, x))
tibble(links) -> links_list
```




